import { Document, Packer, Paragraph, TextRun, HeadingLevel, ImageRun } from 'docx';

async function fetchImageAsArrayBuffer(url: string): Promise<{data: ArrayBuffer, width: number, height: number}> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'Anonymous';
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.drawImage(img, 0, 0);
        const dataUrl = canvas.toDataURL('image/jpeg', 0.9);
        const base64 = dataUrl.split(',')[1];
        const binaryString = window.atob(base64);
        const len = binaryString.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
          bytes[i] = binaryString.charCodeAt(i);
        }
        resolve({
          data: bytes.buffer,
          width: img.width,
          height: img.height
        });
      } else {
        reject(new Error('Canvas context not available'));
      }
    };
    img.onerror = reject;
    img.src = url;
  });
}

export async function exportToWord(content: string, title?: string) {
  const docTitle = title || 'OpenKoma Response';
  
  const blocks = content.split('\n');
  
  const paragraphs: Paragraph[] = [];
  
  // title
  paragraphs.push(new Paragraph({
    text: docTitle,
    heading: HeadingLevel.HEADING_1,
  }));
  
  paragraphs.push(new Paragraph({
    text: `Generated by OpenKoma AI • ${new Date().toLocaleDateString('id-ID', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`,
    style: 'Subtitle',
  }));
  
  paragraphs.push(new Paragraph({ text: '' }));

  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed) {
      paragraphs.push(new Paragraph({ text: '' }));
      continue;
    }
    
    // Check if it's an image
    const imgMatch = /^!\[([^\]]*)\]\(([^)]+)\)$/.exec(trimmed);
    if (imgMatch) {
      const url = imgMatch[2];
      try {
        const { data, width, height } = await fetchImageAsArrayBuffer(url);
        // Calculate max width for word doc (approx 600px)
        let docW = width;
        let docH = height;
        if (docW > 600) {
          const ratio = 600 / docW;
          docW = 600;
          docH = docH * ratio;
        }

        paragraphs.push(new Paragraph({
          children: [
            new ImageRun({
              data: data,
              transformation: {
                width: docW,
                height: docH,
              },
            })
          ],
        }));
      } catch (e) {
        paragraphs.push(new Paragraph({
           children: [new TextRun(`[Image: ${imgMatch[1]}]`)]
        }));
      }
      continue;
    }

    // Very basic markdown parsing
    if (trimmed.startsWith('# ')) {
      paragraphs.push(new Paragraph({ text: trimmed.slice(2), heading: HeadingLevel.HEADING_2 }));
    } else if (trimmed.startsWith('## ')) {
      paragraphs.push(new Paragraph({ text: trimmed.slice(3), heading: HeadingLevel.HEADING_3 }));
    } else if (trimmed.startsWith('### ')) {
      paragraphs.push(new Paragraph({ text: trimmed.slice(4), heading: HeadingLevel.HEADING_4 }));
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      paragraphs.push(new Paragraph({ text: trimmed.slice(2), bullet: { level: 0 } }));
    } else {
      // Inline images
      const parts = trimmed.split(/(!\[[^\]]*\]\([^)]+\))/);
      if (parts.length > 1) {
        // complex paragraph with possible inline images... but we just fallback to text for inline in docx as handling async ImageRun in children array mapping is complex
        const cleanText = trimmed.replace(/!\[([^\]]*)\]\([^)]+\)/g, '[Image: $1]').replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1');
        paragraphs.push(new Paragraph({
           children: [new TextRun(cleanText)]
        }));
      } else {
        const cleanText = trimmed.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1');
        paragraphs.push(new Paragraph({
           children: [new TextRun(cleanText)]
        }));
      }
    }
  }

  const doc = new Document({
    title: docTitle,
    sections: [
      {
        properties: {},
        children: paragraphs
      }
    ]
  });

  const blob = await Packer.toBlob(doc);
  
  // Browser save
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  
  const safeName = docTitle
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 50);
  
  a.download = `${safeName}.docx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
}
