import jsPDF from 'jspdf';

/**
 * Export AI response content as a clean PDF document.
 * Strips markdown formatting and creates a readable PDF.
 */
export async function exportToPDF(content: string, title?: string) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let yPos = margin;

  // Helper: add new page if needed
  const checkPageBreak = (requiredHeight: number) => {
    if (yPos + requiredHeight > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
    }
  };

  // Clean markdown to plain text
  const cleanMarkdown = (text: string): string => {
    return text
      .replace(/```[\s\S]*?```/g, (match) => {
        // Keep code block content but strip fences
        return match.replace(/```\w*\n?/g, '').replace(/```/g, '');
      })
      .replace(/\\\[[\s\S]*?\\\]/g, '[Math Formula]')   // block latex
      .replace(/\\\([\s\S]*?\\\)/g, '[Math]')             // inline latex
      .replace(/\$\$[\s\S]*?\$\$/g, '[Math Formula]')     // $$ latex
      .replace(/\$([^$]+)\$/g, '$1')                       // single $ inline
      .replace(/^#{1,6}\s+/gm, '')                         // headers
      .replace(/\*\*(.+?)\*\*/g, '$1')                     // bold
      .replace(/__(.+?)__/g, '$1')                         // bold
      .replace(/\*(.+?)\*/g, '$1')                         // italic
      .replace(/_(.+?)_/g, '$1')                           // italic
      .replace(/~~(.+?)~~/g, '$1')                         // strikethrough
      .replace(/`(.+?)`/g, '$1')                           // inline code
      .replace(/^\s*[-*+]\s+/gm, '• ')                    // unordered list
      .replace(/^\s*\d+\.\s+/gm, (m) => m)                // keep ordered list
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')             // links
      .replace(/!\[([^\]]*)\]\([^)]+\)/g, '[Image: $1]')   // images
      .replace(/^>\s+/gm, '  ')                            // blockquotes
      .replace(/^\s*---+\s*$/gm, '─'.repeat(40))          // horizontal rule
      .replace(/\n{3,}/g, '\n\n');                          // collapse newlines
  };

  // ---- HEADER ----
  // Brand gradient bar
  doc.setFillColor(0, 212, 255);
  doc.rect(0, 0, pageWidth, 8, 'F');

  yPos = 18;

  // Title
  const docTitle = title || 'OpenKoma Response';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(30, 30, 30);
  doc.text(docTitle, margin, yPos);
  yPos += 8;

  // Subtitle with date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated by OpenKoma AI • ${new Date().toLocaleDateString('id-ID', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`, margin, yPos);
  yPos += 4;

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;

  // ---- BODY ----
  const cleaned = cleanMarkdown(content);
  const paragraphs = cleaned.split('\n');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);

  for (const paragraph of paragraphs) {
    const trimmed = paragraph.trim();
    if (!trimmed) {
      yPos += 3;
      continue;
    }

    // Check if it's a bullet point
    const isBullet = trimmed.startsWith('• ');

    const textToRender = isBullet ? trimmed : trimmed;
    const indentX = isBullet ? margin + 5 : margin;
    const lineMaxWidth = isBullet ? maxWidth - 5 : maxWidth;

    const lines = doc.splitTextToSize(textToRender, lineMaxWidth);
    const blockHeight = lines.length * 5.5;

    checkPageBreak(blockHeight);

    for (const line of lines) {
      doc.text(line, indentX, yPos);
      yPos += 5.5;
    }

    yPos += 2;
  }

  // ---- FOOTER on last page ----
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('OpenKoma — Open Source AI Chat Client', margin, pageHeight - 10);
  doc.text(`Page ${doc.getNumberOfPages()}`, pageWidth - margin - 15, pageHeight - 10);

  // Generate filename from title
  const safeName = (title || 'openkoma-response')
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 50);

  doc.save(`${safeName}.pdf`);
}
