import jsPDF from 'jspdf';

async function fetchImageAsBase64(url: string): Promise<{data: string, width: number, height: number}> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'Anonymous';
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.drawImage(img, 0, 0);
        resolve({
          data: canvas.toDataURL('image/jpeg', 0.9),
          width: img.width,
          height: img.height
        });
      } else {
        reject(new Error('Canvas context not available'));
      }
    };
    img.onerror = reject;
    img.src = url;
  });
}

/**
 * Clean markdown to plain text
 */
function cleanMarkdownText(text: string): string {
  return text
    .replace(/```[\s\S]*?```/g, (match) => {
      return match.replace(/```\w*\n?/g, '').replace(/```/g, '');
    })
    .replace(/\\\[[\s\S]*?\\\]/g, '[Math Formula]')
    .replace(/\\\([\s\S]*?\\\)/g, '[Math]')
    .replace(/\$\$[\s\S]*?\$\$/g, '[Math Formula]')
    .replace(/\$([^$]+)\$/g, '$1')
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/__(.+?)__/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/_(.+?)_/g, '$1')
    .replace(/~~(.+?)~~/g, '$1')
    .replace(/`(.+?)`/g, '$1')
    .replace(/^\s*[-*+]\s+/gm, '• ')
    .replace(/^\s*\d+\.\s+/gm, (m) => m)
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/^>\s+/gm, '  ')
    .replace(/^\s*---+\s*$/gm, '─'.repeat(40))
    .replace(/\n{3,}/g, '\n\n');
}

/**
 * Export AI response content as a clean PDF document.
 * Strips markdown formatting and creates a readable PDF.
 */
export async function exportToPDF(content: string, title?: string) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let yPos = margin;

  const checkPageBreak = (requiredHeight: number) => {
    if (yPos + requiredHeight > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
    }
  };

  // ---- HEADER ----
  doc.setFillColor(0, 212, 255);
  doc.rect(0, 0, pageWidth, 8, 'F');
  yPos = 18;

  const docTitle = title || 'OpenKoma Response';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(30, 30, 30);
  doc.text(docTitle, margin, yPos);
  yPos += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated by OpenKoma AI • ${new Date().toLocaleDateString('id-ID', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`, margin, yPos);
  yPos += 4;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;

  // ---- BODY ----
  // Split into parts by blocks of image elements
  const blocks = content.split('\n');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);

  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed) {
      yPos += 3;
      continue;
    }

    const imgMatch = /^!\[([^\]]*)\]\(([^)]+)\)$/.exec(trimmed);
    
    if (imgMatch) {
      const url = imgMatch[2];
      try {
        const { data: imgData, width: imgW, height: imgH } = await fetchImageAsBase64(url);
        // Calculate size to fit width while maintaining aspect ratio
        let pdfImgW = imgW * 0.264583; // px to mm roughly
        let pdfImgH = imgH * 0.264583;
        
        if (pdfImgW > maxWidth) {
          const ratio = maxWidth / pdfImgW;
          pdfImgW = maxWidth;
          pdfImgH = pdfImgH * ratio;
        }

        checkPageBreak(pdfImgH + 5);
        
        // Center image
        const xPos = margin + (maxWidth - pdfImgW) / 2;
        
        doc.addImage(imgData, 'JPEG', xPos, yPos, pdfImgW, pdfImgH);
        yPos += pdfImgH + 5;
      } catch (e) {
        console.error('Failed to load image for PDF:', e);
        const altText = imgMatch[1] ? `[Image: ${imgMatch[1]}]` : '[Image]';
        checkPageBreak(6);
        doc.text(altText, margin, yPos);
        yPos += 6;
      }
      continue;
    }

    // Attempt to handle smaller inline images too
    const parts = trimmed.split(/(!\[[^\]]*\]\([^)]+\))/);
    let remainingParts = parts.filter(p => p.length > 0);

    for (const part of remainingParts) {
      const inlineImgMatch = part.match(/^!\[([^\]]*)\]\(([^)]+)\)$/);
      if (inlineImgMatch) {
        try {
          const { data: imgData, width: imgW, height: imgH } = await fetchImageAsBase64(inlineImgMatch[2]);
          let pdfImgW = imgW * 0.264583;
          let pdfImgH = imgH * 0.264583;
          
          if (pdfImgW > maxWidth) {
            const ratio = maxWidth / pdfImgW;
            pdfImgW = maxWidth;
            pdfImgH = pdfImgH * ratio;
          }
          checkPageBreak(pdfImgH + 5);
          const xPos = margin + (maxWidth - pdfImgW) / 2;
          doc.addImage(imgData, 'JPEG', xPos, yPos, pdfImgW, pdfImgH);
          yPos += pdfImgH + 5;
        } catch (e) {
           const cleanedText = `[Image: ${inlineImgMatch[1]}]`;
           const lines = doc.splitTextToSize(cleanedText, maxWidth);
           checkPageBreak(lines.length * 5.5);
           doc.text(lines, margin, yPos);
           yPos += (lines.length * 5.5) + 2;
        }
      } else {
        const cleanedText = cleanMarkdownText(part);
        const isBullet = cleanedText.startsWith('• ');
        const textToRender = cleanedText;
        const indentX = isBullet ? margin + 5 : margin;
        const lineMaxWidth = isBullet ? maxWidth - 5 : maxWidth;

        const lines = doc.splitTextToSize(textToRender, lineMaxWidth);
        const blockHeight = lines.length * 5.5;

        checkPageBreak(blockHeight);

        for (const line of lines) {
          doc.text(line, indentX, yPos);
          yPos += 5.5;
        }
      }
    }
    yPos += 2;
  }

  // ---- FOOTER ----
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('OpenKoma — Open Source AI Chat Client', margin, pageHeight - 10);
    doc.text(`Page ${i}`, pageWidth - margin - 15, pageHeight - 10);
  }

  const safeName = (title || 'openkoma-response')
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 50);

  doc.save(`${safeName}.pdf`);
}
