export const AI_PROVIDERS = [
  { id: 'openrouter', name: 'OpenRouter', icon: '🌐', desc: 'Access 100+ models. Free & paid models.', free: true },
  { id: 'gemini', name: 'Google Gemini', icon: '🔵', desc: 'Google\'s Gemini 1.5 Pro & Flash.', free: true },
  { id: 'openai', name: 'OpenAI', icon: '🟢', desc: 'GPT-4o, GPT-4o-mini, o1. Requires key.', free: false },
  { id: 'anthropic', name: 'Anthropic', icon: '🟠', desc: 'Claude 3.5 Sonnet, Claude 3 Opus.', free: false },
  { id: 'github', name: 'GitHub Models', icon: '⚫', desc: 'Access models via GitHub Personal Access Token.', free: true },
  { id: 'github_copilot', name: 'GitHub Copilot', icon: '⚪', desc: 'GitHub Copilot API. Requires valid token or proxy.', free: false },
  { id: 'cohere', name: 'Cohere', icon: '🪶', desc: 'Command R+, Command R, Command Light. Free trial key.', free: true, comingSoon: true },
  { id: 'groq', name: 'Groq', icon: '🔴', desc: 'Ultra-fast inference. Free tier available.', free: true },
  { id: 'ollama', name: 'Ollama (Local)', icon: '🟣', desc: 'Run AI models locally. Completely free.', free: true },
  { id: 'huggingface', name: 'Hugging Face', icon: '🤗', desc: 'Access open-source models via Hugging Face Inference API.', free: true, comingSoon: true },
];

export const AI_MODELS: Record<string, { id: string, name: string, type: 'free' | 'premium', desc: string, cost: string }[]> = {
  openrouter: [
    { id: 'qwen/qwen3-next-80b-a3b-instruct:free', name: 'Qwen3 Next 80B A3B', type: 'free', desc: 'Optimized for fast, stable responses', cost: 'Free' },
    { id: 'baidu/qianfan-ocr-fast:free', name: 'Qianfan-OCR-Fast', type: 'free', desc: 'Multimodal model purpose-built for OCR', cost: 'Free' },
    { id: 'meta-llama/llama-3.3-70b-instruct:free', name: 'Llama 3.3 70B Instruct', type: 'free', desc: 'Multilingual LLM optimized for dialogue', cost: 'Free' },
    { id: 'google/gemma-3-27b-it:free', name: 'Gemma 3 27B', type: 'free', desc: 'Multimodal with 128k context', cost: 'Free' },
    { id: 'venice/uncensored:free', name: 'Venice Uncensored', type: 'free', desc: 'Uncensored instruct-tuned Mistral 24B', cost: 'Free' },
    { id: 'google/gemma-3-12b-it:free', name: 'Gemma 3 12B', type: 'free', desc: 'Multimodal Gemma 3', cost: 'Free' },
    { id: 'google/gemma-3-4b-it:free', name: 'Gemma 3 4B', type: 'free', desc: 'Multimodal Gemma 3', cost: 'Free' },
    { id: 'google/gemma-3n-4b-it:free', name: 'Gemma 3n 4B', type: 'free', desc: 'Optimized for low-resource devices', cost: 'Free' },
    { id: 'google/gemma-3n-2b-it:free', name: 'Gemma 3n 2B', type: 'free', desc: 'Efficient 2B effective parameter model', cost: 'Free' },
    { id: 'nousresearch/hermes-3-llama-3.1-405b:free', name: 'Hermes 3 405B', type: 'free', desc: 'Generalist agentic model based on Llama 3.1', cost: 'Free' },
    { id: 'meta-llama/llama-3.2-3b-instruct:free', name: 'Llama 3.2 3B Instruct', type: 'free', desc: 'Multilingual LLM for reasoning', cost: 'Free' },
    { id: 'openrouter/free', name: 'Free Models Router', type: 'free', desc: 'Smartly routes to available free models', cost: 'Free' },
    { id: 'nvidia/llama-nemotron-embed-vl-1b-v2:free', name: 'Llama Nemotron Embed VL', type: 'free', desc: 'Optimized for multimodal QA retrieval', cost: 'Free' },
    { id: 'tencent/hy3-preview:free', name: 'Tencent Hy3 Preview', type: 'free', desc: 'Tencent MoE model for agentic workflows', cost: 'Free' },
    { id: 'nvidia/nemotron-3-super:free', name: 'Nemotron 3 Super', type: 'free', desc: '120B hybrid MoE model from NVIDIA', cost: 'Free' },
    { id: 'inclusionai/ling-2.6-1t:free', name: 'Ling-2.6-1T', type: 'free', desc: 'Trillion-parameter flagship for fast reasoning', cost: 'Free' },
    { id: 'openai/gpt-oss-120b:free', name: 'GPT-OSS-120B', type: 'free', desc: 'OpenAI 117B MoE for high-reasoning', cost: 'Free' },
    { id: 'openai/gpt-oss-20b:free', name: 'GPT-OSS-20B', type: 'free', desc: 'OpenAI 21B MoE for lower-latency', cost: 'Free' },
    { id: 'minimax/minimax-m2.5:free', name: 'MiniMax M2.5', type: 'free', desc: 'SOTA model for real-world productivity', cost: 'Free' },
    { id: 'z-ai/glm-4.5-air:free', name: 'GLM 4.5 Air', type: 'free', desc: 'Lightweight MoE for agent-centric apps', cost: 'Free' },
    { id: 'poolside/laguna-m.1:free', name: 'Laguna M.1', type: 'free', desc: 'Flagship coding agent from Poolside', cost: 'Free' },
    { id: 'google/gemma-4-31b-it:free', name: 'Gemma 4 31B', type: 'free', desc: 'Google DeepMind multimodal model', cost: 'Free' },
    { id: 'google/gemini-2.0-flash-lite-preview-02-05:free', name: 'Gemini 2.0 Flash Lite', type: 'free', desc: 'Fast & capable for everyday tasks', cost: 'Free' },
    { id: 'openai/gpt-4o', name: 'GPT-4o', type: 'premium', desc: 'Most capable OpenAI model', cost: '$5.00/1M' },
    { id: 'anthropic/claude-3.5-sonnet', name: 'Claude 3.5 Sonnet', type: 'premium', desc: 'Best for writing & analysis', cost: '$3.00/1M' },
    { id: 'google/gemini-1.5-pro', name: 'Gemini 1.5 Pro', type: 'premium', desc: 'Large context window (1M tokens)', cost: '$7.00/1M' },
    { id: 'meta-llama/llama-3.1-405b', name: 'Llama 3.1 405B', type: 'premium', desc: 'Largest open-source model', cost: '$3.00/1M' },
  ],
  gemini: [
    { id: 'gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro Preview', type: 'premium', desc: 'Next-generation Gemini Pro (Preview)', cost: 'Free quota / Paid' },
    { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', type: 'premium', desc: 'Google\'s newest most capable model', cost: 'Free quota / Paid' },
    { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', type: 'free', desc: 'Next-gen fast and versatile model', cost: 'Free quota / Paid' },
    { id: 'gemini-2.0-pro-exp-02-05', name: 'Gemini 2.0 Pro Exp', type: 'premium', desc: 'Experimental 2.0 Pro', cost: 'Free quota' },
    { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', type: 'free', desc: 'Fast, multimodal, capable', cost: 'Free quota / Paid' },
    { id: 'gemini-2.0-flash-lite-preview-02-05', name: 'Gemini 2.0 Flash Lite', type: 'free', desc: 'Cost-effective for high volume tasks', cost: 'Free quota / Paid' },
    { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro', type: 'premium', desc: 'Large context window (2M tokens)', cost: 'Free quota / Paid' },
    { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash', type: 'free', desc: 'Fast and versatile (1M tokens)', cost: 'Free quota / Paid' },
    { id: 'gemini-1.5-flash-8b', name: 'Gemini 1.5 Flash-8B', type: 'free', desc: 'Lightweight for lower latency', cost: 'Free quota / Paid' },
  ],
  openai: [
    { id: 'o3-mini', name: 'o3-mini', type: 'premium', desc: 'Fast reasoning model', cost: 'Paid' },
    { id: 'o1', name: 'o1', type: 'premium', desc: 'Versatile reasoning model', cost: 'Paid' },
    { id: 'o1-mini', name: 'o1-mini', type: 'premium', desc: 'Fast reasoning for code and math', cost: 'Paid' },
    { id: 'o1-preview', name: 'o1-preview', type: 'premium', desc: 'Preview reasoning model', cost: 'Paid' },
    { id: 'gpt-4.5-preview', name: 'GPT-4.5 Preview', type: 'premium', desc: 'OpenAI newest flagship model', cost: 'Paid' },
    { id: 'gpt-4o', name: 'GPT-4o', type: 'premium', desc: 'Most capable OpenAI model', cost: 'Paid' },
    { id: 'gpt-4o-mini', name: 'GPT-4o Mini', type: 'premium', desc: 'Fast and affordable', cost: 'Paid' },
    { id: 'gpt-4-turbo', name: 'GPT-4 Turbo', type: 'premium', desc: 'Previous generation flagship', cost: 'Paid' },
    { id: 'gpt-4', name: 'GPT-4', type: 'premium', desc: 'Legacy GPT-4 model', cost: 'Paid' },
    { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo', type: 'premium', desc: 'Legacy fast model', cost: 'Paid' },
  ],
  anthropic: [
    { id: 'claude-3-7-sonnet-20250219', name: 'Claude 3.7 Sonnet', type: 'premium', desc: 'Most intelligent, hybrid reasoning', cost: 'Paid' },
    { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet (Latest)', type: 'premium', desc: 'Fast and powerful for complex tasks', cost: 'Paid' },
    { id: 'claude-3-5-sonnet-20240620', name: 'Claude 3.5 Sonnet (Legacy)', type: 'premium', desc: 'Previous 3.5 Sonnet version', cost: 'Paid' },
    { id: 'claude-3-5-haiku-20241022', name: 'Claude 3.5 Haiku', type: 'premium', desc: 'Fastest Claude model', cost: 'Paid' },
    { id: 'claude-3-opus-20240229', name: 'Claude 3 Opus', type: 'premium', desc: 'Excels at complex analysis', cost: 'Paid' },
    { id: 'claude-3-sonnet-20240229', name: 'Claude 3 Sonnet', type: 'premium', desc: 'Balanced strike rate', cost: 'Paid' },
    { id: 'claude-3-haiku-20240307', name: 'Claude 3 Haiku', type: 'premium', desc: 'Legacy fast model', cost: 'Paid' },
  ],
  github: [
    { id: 'gpt-4o', name: 'GPT-4o', type: 'free', desc: 'OpenAI Flagship Model', cost: 'Free Rate Limits' },
    { id: 'gpt-4o-mini', name: 'GPT-4o-mini', type: 'free', desc: 'OpenAI Small Model', cost: 'Free Rate Limits' },
    { id: 'o1', name: 'o1', type: 'free', desc: 'OpenAI o1 Reasoning Model', cost: 'Free Rate Limits' },
    { id: 'o1-mini', name: 'o1-mini', type: 'free', desc: 'OpenAI o1-mini Reasoning Model', cost: 'Free Rate Limits' },
    { id: 'o1-preview', name: 'o1-preview', type: 'free', desc: 'OpenAI o1-preview Model', cost: 'Free Rate Limits' },
    { id: 'o3-mini', name: 'o3-mini', type: 'free', desc: 'OpenAI o3-mini Reasoning Model', cost: 'Free Rate Limits' },
    { id: 'Meta-Llama-3.1-405B-Instruct', name: 'Llama 3.1 405B Instruct', type: 'free', desc: 'Meta Open Model', cost: 'Free Rate Limits' },
    { id: 'Meta-Llama-3.1-70B-Instruct', name: 'Llama 3.1 70B Instruct', type: 'free', desc: 'Meta Open Model', cost: 'Free Rate Limits' },
    { id: 'Meta-Llama-3.1-8B-Instruct', name: 'Llama 3.1 8B Instruct', type: 'free', desc: 'Meta Small Model', cost: 'Free Rate Limits' },
    { id: 'Phi-4', name: 'Phi-4', type: 'free', desc: 'Microsoft High-End Small Model', cost: 'Free Rate Limits' },
    { id: 'Phi-3.5-mini-instruct', name: 'Phi-3.5 mini', type: 'free', desc: 'Microsoft Small Model', cost: 'Free Rate Limits' },
    { id: 'Phi-3.5-MoE-instruct', name: 'Phi-3.5 MoE', type: 'free', desc: 'Microsoft MoE Model', cost: 'Free Rate Limits' },
    { id: 'Mistral-large', name: 'Mistral Large', type: 'free', desc: 'Mistral Flagship Model', cost: 'Free Rate Limits' },
    { id: 'Mistral-small', name: 'Mistral Small', type: 'free', desc: 'Mistral Capability Model', cost: 'Free Rate Limits' },
    { id: 'Mistral-Nemo', name: 'Mistral Nemo', type: 'free', desc: 'Mistral Partner Model', cost: 'Free Rate Limits' },
    { id: 'Cohere-command-r-plus', name: 'Command R+', type: 'free', desc: 'Cohere Flagship Model', cost: 'Free Rate Limits' },
    { id: 'Cohere-command-r-plus-08-2024', name: 'Command R+ (08-2024)', type: 'free', desc: 'Cohere Flagship Model Updated', cost: 'Free Rate Limits' },
    { id: 'Cohere-command-r', name: 'Command R', type: 'free', desc: 'Cohere Model', cost: 'Free Rate Limits' },
    { id: 'Cohere-command-r-08-2024', name: 'Command R (08-2024)', type: 'free', desc: 'Cohere Model Updated', cost: 'Free Rate Limits' },
    { id: 'AI21-Jamba-1.5-Large', name: 'AI21 Jamba 1.5 Large', type: 'free', desc: 'AI21 SSM+Transformer MoE Model', cost: 'Free Rate Limits' },
    { id: 'AI21-Jamba-1.5-Mini', name: 'AI21 Jamba 1.5 Mini', type: 'free', desc: 'AI21 SSM+Transformer MoE Model', cost: 'Free Rate Limits' },
  ],
  github_copilot: [
    { id: 'gpt-4o', name: 'GPT-4o', type: 'premium', desc: 'OpenAI Flagship Model', cost: 'Copilot Token' },
    { id: 'gpt-4o-mini', name: 'GPT-4o Mini', type: 'premium', desc: 'OpenAI Small Model', cost: 'Copilot Token' },
    { id: 'gpt-4', name: 'GPT-4', type: 'premium', desc: 'OpenAI GPT-4', cost: 'Copilot Token' },
    { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo', type: 'free', desc: 'OpenAI Fast Model', cost: 'Copilot Token' },
    { id: 'claude-3.5-sonnet', name: 'Claude 3.5 Sonnet', type: 'premium', desc: 'Anthropic Model', cost: 'Copilot Token' }
  ],
  cohere: [
    { id: 'command-r-plus', name: 'Command R+', type: 'free', desc: 'Flagship model for complex reasoning and RAG', cost: 'Free Trial' },
    { id: 'command-r', name: 'Command R', type: 'free', desc: 'Fast, strong reasoning and multilingual', cost: 'Free Trial' },
    { id: 'command-light', name: 'Command Light', type: 'free', desc: 'Super fast for simple tasks', cost: 'Free Trial' }
  ],
  groq: [
    { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B', type: 'free', desc: 'Fast Llama 3.3 70B', cost: 'Free' },
    { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B', type: 'free', desc: 'Ultra-fast inference', cost: 'Free' },
    { id: 'qwen/qwen3-32b', name: 'Qwen 3 32B', type: 'free', desc: 'Fast Qwen 3 32B', cost: 'Free' },
    { id: 'openai/gpt-oss-120b', name: 'GPT-OSS 120B', type: 'free', desc: 'GPT MoE 120B', cost: 'Free' },
    { id: 'openai/gpt-oss-20b', name: 'GPT-OSS 20B', type: 'free', desc: 'GPT MoE 20B', cost: 'Free' },
    { id: 'groq/compound', name: 'Groq Compound', type: 'free', desc: 'Compound Model', cost: 'Free' },
    { id: 'groq/compound-mini', name: 'Groq Compound Mini', type: 'free', desc: 'Compound Mini', cost: 'Free' },
    { id: 'meta-llama/llama-4-scout-17b-16e-instruct', name: 'Llama 4 Scout 17B', type: 'free', desc: 'Llama 4 Scout', cost: 'Free' },
    { id: 'canopylabs/orpheus-v1-english', name: 'Orpheus v1 English', type: 'free', desc: 'Canopy Labs Orpheus', cost: 'Free' },
    { id: 'canopylabs/orpheus-arabic-saudi', name: 'Orpheus Arabic Saudi', type: 'free', desc: 'Canopy Labs Orpheus Arabic', cost: 'Free' },
    { id: 'whisper-large-v3', name: 'Whisper Large v3', type: 'free', desc: 'Speech to text', cost: 'Free' },
    { id: 'whisper-large-v3-turbo', name: 'Whisper Large v3 Turbo', type: 'free', desc: 'Speech to text fast', cost: 'Free' },
  ],
  ollama: [
    { id: 'llama3', name: 'Llama 3', type: 'free', desc: 'Local Llama 3 8B', cost: 'Free' },
    { id: 'mistral', name: 'Mistral', type: 'free', desc: 'Local Mistral 7B', cost: 'Free' },
  ],
  huggingface: [
    { id: 'meta-llama/Meta-Llama-3-8B-Instruct', name: 'Llama 3 8B Instruct', type: 'free', desc: 'Capable open model from Meta', cost: 'Free' },
    { id: 'meta-llama/Meta-Llama-3-70B-Instruct', name: 'Llama 3 70B Instruct', type: 'free', desc: 'Powerful open model from Meta', cost: 'Free' },
    { id: 'mistralai/Mistral-7B-Instruct-v0.3', name: 'Mistral 7B Instruct', type: 'free', desc: 'Strong 7B model from Mistral AI', cost: 'Free' },
    { id: 'mistralai/Mixtral-8x7B-Instruct-v0.1', name: 'Mixtral 8x7B Instruct', type: 'free', desc: 'Fast MoE model from Mistral AI', cost: 'Free' },
    { id: 'google/gemma-7b-it', name: 'Gemma 7B IT', type: 'free', desc: 'Google Deepmind Gemma 7B', cost: 'Free' },
    { id: 'HuggingFaceH4/zephyr-7b-beta', name: 'Zephyr 7B Beta', type: 'free', desc: 'Fine-tuned Mistral 7B', cost: 'Free' },
    { id: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen 2.5 72B', type: 'free', desc: 'Advanced large model from Alibaba', cost: 'Free' },
    { id: 'Qwen/Qwen2.5-7B-Instruct', name: 'Qwen 2.5 7B', type: 'free', desc: 'Capable small model from Alibaba', cost: 'Free' },
    { id: 'microsoft/Phi-3-mini-4k-instruct', name: 'Phi-3 Mini 4K', type: 'free', desc: 'Lightweight model from Microsoft', cost: 'Free' },
    { id: 'deepseek-ai/DeepSeek-Coder-V2-Instruct', name: 'DeepSeek Coder V2', type: 'free', desc: 'Great for coding', cost: 'Free' },
  ]
};

export function getProviderName(providerId: string): string {
  return AI_PROVIDERS.find(p => p.id === providerId)?.name || 'Unknown';
}

export function isProviderFree(providerId: string): boolean {
  return AI_PROVIDERS.find(p => p.id === providerId)?.free || false;
}
